import { FeatureComponents } from './feature-components.constant';

export const ACCESS_LEVEL = {
    CHECKER: 'CHECKER',
    AUTHORIZER_1: 'AUTHORIZER_1',
    AUTHORIZER_2: 'AUTHORIZER_2',
    AUTHORIZER_3: 'AUTHORIZER_3',
    AUTHORIZER_4: 'AUTHORIZER_4',
    NO_ACCESS: 'NO_ACCESS',
    VIEWER: 'VIEWER',
    SUPER_USER: 'SUPER_USER',
    MAKER: 'MAKER',
} as const;

export const ACCESS_LEVEL_AS_NUMERIC_VALUE = {
    CHECKER: 2,
    AUTHORIZER_1: 3,
    AUTHORIZER_2: 4,
    AUTHORIZER_3: 5,
    AUTHORIZER_4: 6,
    NO_ACCESS: 0,
    VIEWER: 0,
    SUPER_USER: 7,
    MAKER: 1,
} as const;

export const ACCESS_LEVEL_NUMBER_TO_STR = {
    2: 'CHECKER',
    3: 'AUTHORIZER_1',
    4: 'AUTHORIZER_2',
    5: 'AUTHORIZER_3',
    6: 'AUTHORIZER_4',
    0: 'VIEWER',
    '-1': 'NO_ACCESS',
    7: 'SUPER_USER',
    1: 'MAKER',
} as const;

export const IMMEDIATE_NEXT_ACCESS_LEVELS = {
    [ACCESS_LEVEL.NO_ACCESS]: [ACCESS_LEVEL.MAKER],
    [ACCESS_LEVEL.VIEWER]: [ACCESS_LEVEL.MAKER],
    [ACCESS_LEVEL.MAKER]: [ACCESS_LEVEL.CHECKER],
    [ACCESS_LEVEL.CHECKER]: [ACCESS_LEVEL.AUTHORIZER_1],
    [ACCESS_LEVEL.AUTHORIZER_1]: [ACCESS_LEVEL.AUTHORIZER_2],
    [ACCESS_LEVEL.AUTHORIZER_2]: [ACCESS_LEVEL.AUTHORIZER_3],
    [ACCESS_LEVEL.AUTHORIZER_3]: [ACCESS_LEVEL.AUTHORIZER_4],
    [ACCESS_LEVEL.AUTHORIZER_4]: [ACCESS_LEVEL.SUPER_USER],
    [ACCESS_LEVEL.SUPER_USER]: [],
};

export const AUTHORIZATION_FLOW_FOR_FEATURES = {
    [FeatureComponents.FINANCE.INPUT_OPTS.SYSTEM_SETTINGS.ID]: [
        ACCESS_LEVEL.MAKER,
        ACCESS_LEVEL.CHECKER,
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
    ],

    [FeatureComponents.FINANCE.INPUT_OPTS.REVENUE_SETTLEMENT_FEE_RATES.ID]: [
        ACCESS_LEVEL.MAKER,
        ACCESS_LEVEL.CHECKER,
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
    ],
    [FeatureComponents.FINANCE.INPUT_OPTS.DELIVERY_CHARGES.ID]: [
        ACCESS_LEVEL.MAKER,
        ACCESS_LEVEL.CHECKER,
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
    ],
    [FeatureComponents.FINANCE.INPUT_OPTS.GOLD_QUOTA.ID]: [
        ACCESS_LEVEL.MAKER,
        ACCESS_LEVEL.CHECKER,
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
    ],

    [FeatureComponents.CRM.APP_USERS.LIST.ID]: [ACCESS_LEVEL.SUPER_USER],
    [FeatureComponents.CRM.CHANGE_REQUESTS.PENDING.ID]: [
        ACCESS_LEVEL.CHECKER,
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
    ],

    [FeatureComponents.FINANCE.DISPUTES.LIST.ID]: [
        ACCESS_LEVEL.MAKER,
        ACCESS_LEVEL.CHECKER,
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.SUPER_USER,
        ],
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.SUPER_USER,
        ],
    ],

    [FeatureComponents.FINANCE.SPECIAL_TRANSACTIONS.LIST.ID]: [
        ACCESS_LEVEL.MAKER,
        ACCESS_LEVEL.CHECKER,
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.SUPER_USER,
        ],
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.SUPER_USER,
        ],
    ],
    [FeatureComponents.FINANCE.DISBURSEMENTS.LIST.ID]: [
        ACCESS_LEVEL.CHECKER,
        [ACCESS_LEVEL.AUTHORIZER_1, ACCESS_LEVEL.SUPER_USER],
    ],
    [FeatureComponents.MARKETING.APP_BANNER.LIST.ID]: [
        ACCESS_LEVEL.MAKER,
        ACCESS_LEVEL.CHECKER,
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
    ],
    [FeatureComponents.MARKETING.APP_NOTIFICATION.LIST.ID]: [
        ACCESS_LEVEL.MAKER,
        ACCESS_LEVEL.CHECKER,
        [
            ACCESS_LEVEL.AUTHORIZER_1,
            ACCESS_LEVEL.AUTHORIZER_2,
            ACCESS_LEVEL.AUTHORIZER_3,
            ACCESS_LEVEL.AUTHORIZER_4,
            ACCESS_LEVEL.SUPER_USER,
        ],
    ],
} as const;
