version: '3'

services:
  redis_app:
    build:
      context: .
      dockerfile: Dockerfile # Adjust if your Dockerfile has a different name
    container_name: pure-frontend
    restart: always
    ports:
      - '3030:3030'
    networks:
      admin-pure-backend_pure_backend:
        ipv4_address: 192.168.10.22

networks:
  admin-pure-backend_pure_backend:
    external: true
