# docker-compose.yml
services:
  app:
    build:
      context: .
      target: development # Use the development stage from Dockerfile
    container_name: taskshpere-app
    ports:
      - "${APP_PORT_HOST:-3000}:${PORT:-3000}" # Map host port 3000 to container port 3000
    volumes:
      - .:/usr/src/app # Mount current directory to app directory in container (for hot-reloading)
      - /usr/src/app/node_modules # Prevent host node_modules from overwriting container's
      - /usr/src/app/dist # Ensure dist is not overwritten by host if it exists
    env_file:
      - .env.local # Load environment variables from .env.local
    depends_on:
      db:
        condition: service_healthy # Wait for DB to be healthy
    restart: unless-stopped
    networks:
      - taskshpere-network

  db:
    image: postgres:15-alpine # Or postgres:latest
    container_name: taskshpere-db
    ports:
      - "${DB_PORT_HOST:-5432}:5432" # Map host port 5432 to container port 5432
    environment:
      POSTGRES_USER: root         # CHANGE THIS
      POSTGRES_PASSWORD: 123456   # CHANGE THIS
      POSTGRES_DB: taskapp         # CHANGE THIS
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist database data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d taskapp"] # CHANGE youruser and yourdbname
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - taskshpere-network

volumes:
  pgdata: # Named volume for PostgreSQL data persistence

networks:
  taskshpere-network:
    driver: host