const fs = require('fs');
const { flags } = require('../src/lib/feature-flag/index');
const path = require('path');

const filePath = path.join(
  __dirname,
  '..',
  'src',
  'types',
  'feature-flags.d.ts'
);

/* eslint-disable @typescript-eslint/no-var-requires */
// Write typescript definitions for global variables
// eslint-disable-next-line prettier/prettier
const definitions = 
  `declare var __FEATURE_FLAGS__ = {\n${Object.keys(flags)
  .map((name) => `  ${name}: boolean,`)
  .join('\n')}\n}`;

fs.writeFileSync(
  filePath,
  '// This file is automatically generated, do not edit manually!\n'
);
fs.appendFileSync(filePath, definitions);
